### ISSUE TITLE
shift on the detected boxes

### ISSUE THREAD

**Issue by clorislili** [nickgkan/beauty_detr#2] opened 2022-10-08 11:27 UTC
Hi, I visualize the detected boxes (before random shift augmentation) on the point cloud scene, but realize that there is a consistent shift existed. After generating target box based on the point cloud scene, it resulted in 0.0 iou due to the shift. Would you plz public the detector backbone training code? Or any other ways to solve this problem?  Thanks in advance!

**Comment by ayushjain1144** [comment] 2022-10-08 22:37
Hi @clorislili, just to get more information, are you facing this issue with the predictions we saved or you are training a detector and saving the predictions yourself?

**Comment by clorislili** [comment] 2022-10-09 02:49
@ayushjain1144 Thanks for your reply. Yes, with the predicted boxes you offered. Specifically, I visualized the all_detected_boxes after 590 line in joint_det_dataset.py before any augmentation. And the point cloud scene I use followed referit3d codebase, I believe there is no shift option in the point cloud scene. When I visualize detected boxes and point cloud scene together, it can not overlap, some shift existed between boxes and point cloud scene. Maybe the way you deal with pointc cloud scene is different from referit3d?

**Comment by clorislili** [comment] 2022-10-09 03:17
![658d9a18d842af64cdba37be](https://user-images.githubusercontent.com/71256919/194736134-0f7bd08b-c247-48b8-9a9e-e8ea5287afdc.jpg)
Can you see the shift of the boxes and the corresponding point cloud object?

**Comment by ayushjain1144** [comment] 2022-10-09 03:58
Yep! Clearly it looks incorrect. Which visualization code are you using? I am wondering because we haven't tested the visualization code in our dataloader for a long time, so maybe there is a bug there that we can look into. 

Most likely though, I think the issue is related to using PC loaded by referit instead of our dataloader (we can look into it and get back to you on how you can fix that). Did you try visualizing the PC loaded by us and our detected boxes?

**Comment by clorislili** [comment] 2022-10-09 04:17
The visualization code i use is yours, the wandb.3d visualizer. I think the problem does not lie here. I'm trying to use the PC by yours now, hope I can find where the problem is. Get back to me if you have got any progress. Thanks!

**Comment by ayushjain1144** [comment] 2022-10-09 04:50
https://wandb.ai/ayushjain1144/vis/runs/2ovse3wg?workspace=user-ayushjain1144 : I visualized the detected boxes with our pointcloud, I think it looks pretty reasonable.

**Comment by clorislili** [comment] 2022-10-09 07:24
Yeah, I figured it. It's because of the PC data. I will alter to your PC dataloader. Thanks a lot!

**Comment by clorislili** [comment] 2022-10-09 11:32
Also, in the detected boxes file, I only see train and test boxes, will you public the validation detected boxes? Thanks

**Comment by ayushjain1144** [comment] 2022-10-09 17:24
Great that you figured it out! Closing this issue, but please feel free to ask any other questions you might have!

**Closed as completed by ayushjain1144** 2022-10-09 17:24 UTC

**Comment by IISCAditayTripathi** [comment] 2023-04-25 09:14
What was the issue @ayushjain1144 and @clorislili ?

**Comment by ayushjain1144** [comment] 2023-04-25 19:47
Hi @IISCAditayTripathi, @clorislili debugged it themselves so I am not sure, but I believe the issue was visualizing the bounding boxes we provide with pointclouds from some other repo and there is likely some mismatch in coordinate system/alignment.
